IEx.configure(inspect: [charlists: :as_lists])

alias NorthwindElixirTraders.Repo
alias NorthwindElixirTraders.Category
alias NorthwindElixirTraders.Employee
alias NorthwindElixirTraders.Supplier
alias NorthwindElixirTraders.Shipper
alias NorthwindElixirTraders.Customer
alias NorthwindElixirTraders.Product
alias NorthwindElixirTraders.Country
alias NorthwindElixirTraders.Order
alias NorthwindElixirTraders.OrderDetail
alias NorthwindElixirTraders.DataImporter
alias NorthwindElixirTraders.Insights

import Ecto.Query
